apiVersion: v1
kind: Service
metadata:
  name: nombre1
spec:
  type: NodePort
  selector:
    app: nombre1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: puerto_phpmyadmin