apiVersion: apps/v1
kind: Deployment
metadata:
  name: nombre4
spec:
  replicas: repliques
  selector:
    matchLabels:
      app: nombre4
  template:
    metadata:
      labels:
        app: nombre4
    spec:
      containers:
      - name: php-apache
        image: php:7.4-apache
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-content
          mountPath: /var/www/html
